[avr]
exten => s,1,Answer()
 same => n,Ringing()
 same => n,Wait(1)
 same => n,Set(UUID=${SHELL(uuidgen | tr -d '\n')})
 same => n,Set(DENOISE(rx)=on)
 same => n,Dial(AudioSocket/${ARG1}/${UUID})
 same => n,Hangup()

[demo]

exten => s,1,GoSub(avr,s,1(avr-core:5001))
exten => 5001,1,GoSub(avr,s,1(avr-core:5001))
exten => 5002,1,GoSub(avr,s,1(host.docker.internal:5001))

exten => 5003,1,NoOp(HTTP endpoint example)
 same => n,Answer()
 same => n,Ringing()
 same => n,Wait(1)
 same => n,Set(UUID=${SHELL(uuidgen | tr -d '\n')})
 same => n,Set(JSON_BODY={"uuid":"${UUID}","payload":{"from":"${CALLERID(num)}","to":"${EXTEN}","uniqueid":"${UNIQUEID}","channel":"${CHANNEL}","recording": false}})
 same => n,Set(CURLOPT(httpheader)=Content-Type: application/json)
 same => n,Set(JSON_RESPONSE=${CURL(http://avr-core:6001/call,${JSON_BODY})})
 same => n,Set(DENOISE(rx)=on)
 same => n,Dial(AudioSocket/avr-core:5001/${UUID})
 same => n,Hangup()

; Route incoming ViciDial agent phone calls to AVR/VAPI
exten => gs102,1,GoSub(avr,s,1(avr-core:5001))
exten => 201,1,GoSub(avr,s,1(avr-core:5001))

[from-vicidial]
exten => s,1,Answer()
 same => n,Ringing()
 same => n,Wait(1)
 same => n,Set(UUID=${SHELL(uuidgen | tr -d '\n')})
 same => n,Set(JSON_BODY={"uuid":"${UUID}","payload":{"from":"${CALLERID(num)}","to":"${EXTEN}","uniqueid":"${UNIQUEID}","channel":"${CHANNEL}","recording":false}})
 same => n,Set(CURLOPT(httpheader)=Content-Type: application/json)
 same => n,Set(JSON_RESPONSE=${CURL(http://avr-core:6001/call,${JSON_BODY})})
 same => n,NoOp(avr-core STS: ${JSON_RESPONSE})
 same => n,Set(DENOISE(rx)=on)
 same => n,Dial(AudioSocket/avr-core:5001/${UUID})
 same => n,Hangup()
exten => gs102,1,Goto(s,1)
exten => 201,1,Goto(s,1)
exten => 5001,1,Goto(s,1)
